apiVersion: v1
kind: Service
metadata:
  name: robot-dh-api
  namespace: robot-dh
spec:
  type: NodePort
  selector:
    app: robot-dh-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
