apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: robot-dh-local-ml-ready-
  namespace: robot-dh
  labels:
    app: robot-dh
    component: v1-7-local
    role: devscale-ml-ready
spec:
  workflowTemplateRef:
    name: robot-dh-local-ml-ready
